dist: focal

addons:
  postgresql: "12"
  apt:
    update: true
    packages:
      - postgresql-12-postgis-3

jobs:
  include:
    - stage: tests
      language: python
      python: "3.9"
      install:
          ### Proceed with the install of py3dtilers per se.
          # The extra flag installs the dev dependencies, refer to e.g.
          # https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
        - pip install -e .[dev,prod]
        - python -c 'import ifcopenshell'  # Just to make sure
      script:
      - |
        flake8 .
        pytest
    - stage: "Markdown link checks"
      language: node_js
      node_js: 16
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi
